FROM node:alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node package.json ./

# RUN npm config set unsafe-perm true

RUN npm install 

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]